VirtoCommerce.CartModule.Data/Services/ShoppingCartServiceImpl.cs

We want to be able to search on fields that are defined on extended shopping cart type. For this we need to be able to manipulate the query & sorting.

Separate GetQuery & GetSortings + make them overridable in ShoppingCartSearchService

---

VirtoCommerce.CartModule.Data/Services/ShoppingCartServiceImpl.cs

fix Paged search ordering revision

---

VirtoCommerce.CartModule.Data/Repositories/CartRepositoryImpl.cs

used isNullOrEmpty
minor reformat

Empty collection request optimization

---

src/VirtoCommerce.CartModule.Data/Migrations/20191016085759_MissedChangesFromSecondVersion.Designer.cs
src/VirtoCommerce.CartModule.Data/Migrations/20191016085759_MissedChangesFromSecondVersion.cs
src/VirtoCommerce.CartModule.Data/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/LineItemEntity.cs
src/VirtoCommerce.CartModule.Data/Model/ShipmentEntity.cs
src/VirtoCommerce.CartModule.Data/Model/ShipmentItemEntity.cs
src/VirtoCommerce.CartModule.Data/Model/ShoppingCartEntity.cs
src/VirtoCommerce.CartModule.Data/Repositories/CartRepository.cs
src/VirtoCommerce.CartModule.Data/Repositories/ICartRepository.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartSearchService.cs
src/VirtoCommerce.CartModule.Web/Controllers/Api/CartModuleController.cs

From issue https://virtocommerce.atlassian.net/projects/VP/issues/VP-670

BE: Missed changes from second version.

---

VirtoCommerce.CartModule.Web/Controllers/Api/CartModuleController.cs

vp-1126_move_CORS_manage_to_platform

---

VirtoCommerce.CartModule.Data/Model/ShoppingCartEntity.cs
VirtoCommerce.CartModule.Data/Services/IShoppingCartBuilder.cs
VirtoCommerce.CartModule.Data/Services/ShoppingCartBuilderImpl.cs
VirtoCommerce.CartModule.Web/Controllers/Api/CartModuleController.cs

The pull request was trying to finalize the pull request created by @yecli https://github.com/VirtoCommerce/vc-module-cart/pull/31
To make sure add a coupon and remove a coupon should work which is not at this moment.

fix: Add a coupon and remove a coupon should work

---

src/VirtoCommerce.CartModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3114

VP-3114: Fix logo

---

src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs

VP-5334: Call ClearCache before publish event
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5334: Call ClearCache before publish event

---

src/VirtoCommerce.CartModule.Data/Repositories/CartRepository.cs

Also, reduces number of queries by twice
https://virtocommerce.atlassian.net/browse/VP-6911

VP-6911: Remove cart through plain query

---

src/VirtoCommerce.CartModule.Data/Repositories/CartRepository.cs

Reverts VirtoCommerce/vc-module-cart#73

Revert "VP-6911: Remove cart through plain query"

---

src/VirtoCommerce.CartModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/VP-6905

VP-6905 remove call to BuildServiceProvider

---

src/VirtoCommerce.CartModule.Data/Repositories/CartRepository.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs

https://virtocommerce.atlassian.net/browse/VP-6911

VP-6911: Implement cart soft remove thru plain query

---

src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs
src/VirtoCommerce.CartModule.Data/Validation/AddressValidator.cs
src/VirtoCommerce.CartModule.Data/Validation/CartValidator.cs
src/VirtoCommerce.CartModule.Data/Validation/PaymentValidator.cs
src/VirtoCommerce.CartModule.Data/Validation/ShipmentValidator.cs
src/VirtoCommerce.CartModule.Web/Controllers/Api/CartModuleController.cs
tests/VirtoCommerce.CartModule.Tests/UnitTests/ShoppingCartServiceImplUnitTests.cs

https://virtocommerce.atlassian.net/browse/PT-159
Add fluent validation to ShoppingCartService so that this 
would be replaced by BadRequest:

PT-328: Add cart validation

---

src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-207

PT-207: Enable Source link support

---

src/VirtoCommerce.CartModule.Data/Model/LineItemEntity.cs

https://virtocommerce.atlassian.net/browse/PT-830

PT-1673 add FulfillmentCenter Id-Name model-entity binding in Line item

---

src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs

https://virtocommerce.atlassian.net/browse/PT-1318

PT-1319: Wrong status in event when user use softDelete for cart

---

.github/workflows/deploy-pr.yml
src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data/Services/DefaultShoppingCartTotalsCalculator.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/module.manifest
tests/VirtoCommerce.CartModule.Tests/UnitTests/CartTotalsCalculationTests.cs
tests/VirtoCommerce.CartModule.Tests/UnitTests/ShoppingCartServiceImplUnitTests.cs
tests/VirtoCommerce.CartModule.Tests/VirtoCommerce.CartModule.Tests.csproj

PT-1924: Use rouding policies

---

src/VirtoCommerce.CartModule.Core/Model/LineItem.cs
src/VirtoCommerce.CartModule.Data/Migrations/20210906103519_IsRejectedLineitem.Designer.cs
src/VirtoCommerce.CartModule.Data/Migrations/20210906103519_IsRejectedLineitem.cs
src/VirtoCommerce.CartModule.Data/Model/LineItemEntity.cs
src/VirtoCommerce.CartModule.Data/Services/DefaultShoppingCartTotalsCalculator.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
tests/VirtoCommerce.CartModule.Tests/UnitTests/CartTotalsCalculationTests.cs

PT-3181: Add IsRejected to LineItem, skip gifts in default totals calculator

---

src/VirtoCommerce.CartModule.Data/Repositories/CartRepository.cs

Soft-deleted carts should never be read
https://virtocommerce.atlassian.net/browse/PT-4621

PT-4621: Soft-deleted carts should never be read

---

.github/workflows/main.yml
.github/workflows/publish_nugets.yml
Directory.Build.props
src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data/Repositories/CartDbContext.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/VirtoCommerce.CartModule.Web.csproj
src/VirtoCommerce.CartModule.Web/module.manifest
tests/VirtoCommerce.CartModule.Tests/UnitTests/ShoppingCartServiceImplUnitTests.cs
tests/VirtoCommerce.CartModule.Tests/VirtoCommerce.CartModule.Tests.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/VirtoCommerce.CartModule.Web.csproj

PT-6404: Fix empty sonar codecoverage report

---

src/VirtoCommerce.CartModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-7292

PT-7292: Remove redundant BuildServiceProvider from the module startup

---

src/VirtoCommerce.CartModule.Data/Repositories/CartDbContext.cs

Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152

PT-9152: Fix EF validation runtime warnings

---

VirtoCommerce.CartModule.sln.DotSettings
src/VirtoCommerce.CartModule.Core/Services/IWishlistService.cs
src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs
src/VirtoCommerce.CartModule.Data/Services/WishlistService.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/Module.cs
src/VirtoCommerce.CartModule.Web/VirtoCommerce.CartModule.Web.csproj
src/VirtoCommerce.CartModule.Web/module.manifest
tests/VirtoCommerce.CartModule.Tests/UnitTests/PlatformMemoryCache.cs
tests/VirtoCommerce.CartModule.Tests/UnitTests/ShoppingCartServiceImplUnitTests.cs
tests/VirtoCommerce.CartModule.Tests/VirtoCommerce.CartModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-9697

PT-9697: Add wishlist service

---

src/VirtoCommerce.CartModule.Data/Services/WishlistService.cs

https://virtocommerce.atlassian.net/browse/PT-10934

PT-10934: Fix wishlist lineitems cache

---

src/VirtoCommerce.CartModule.Core/Model/Payment.cs
src/VirtoCommerce.CartModule.Core/Model/Shipment.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20230413103904_AddShipmentAndPaymentComment.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20230413103904_AddShipmentAndPaymentComment.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20230413103928_AddShipmentAndPaymentComment.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20230413103928_AddShipmentAndPaymentComment.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20230413103617_AddShipmentAndPaymentComment.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20230413103617_AddShipmentAndPaymentComment.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/PaymentEntity.cs
src/VirtoCommerce.CartModule.Data/Model/ShipmentEntity.cs

Add properties:
- shipment comment
- payment comment
- payment purpose

Add comment to cart shipments and payments

---

.github/CODEOWNERS
docs/index.md

https://virtocommerce.atlassian.net/browse/PT-12263

PT-12263: add cart deletion override documentation

---

.editorconfig
Directory.Build.props
VirtoCommerce.CartModule.sln.DotSettings
module.ignore
src/VirtoCommerce.CartModule.Core/Services/IShoppingCartSearchService.cs
src/VirtoCommerce.CartModule.Core/Services/IShoppingCartService.cs
src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data.MySql/MySqlCartRawDatabaseCommand.cs
src/VirtoCommerce.CartModule.Data.MySql/VirtoCommerce.CartModule.Data.MySql.csproj
src/VirtoCommerce.CartModule.Data.PostgreSql/PostgreSqlCartRawDatabaseCommandcs.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/VirtoCommerce.CartModule.Data.PostgreSql.csproj
src/VirtoCommerce.CartModule.Data.SqlServer/SqlServerCartRawDatabaseCommand.cs
src/VirtoCommerce.CartModule.Data.SqlServer/VirtoCommerce.CartModule.Data.SqlServer.csproj
src/VirtoCommerce.CartModule.Data/BackgroundJobs/DeleteObsoleteCartsHandler.cs
src/VirtoCommerce.CartModule.Data/Model/AddressEntity.cs
src/VirtoCommerce.CartModule.Data/Repositories/CartRepository.cs
src/VirtoCommerce.CartModule.Data/Repositories/ICartRawDatabaseCommand.cs
src/VirtoCommerce.CartModule.Data/Repositories/ICartRepository.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartBuilder.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartSearchService.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs
src/VirtoCommerce.CartModule.Data/Services/WishlistService.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/Controllers/Api/CartModuleController.cs
src/VirtoCommerce.CartModule.Web/Module.cs
src/VirtoCommerce.CartModule.Web/VirtoCommerce.CartModule.Web.csproj
src/VirtoCommerce.CartModule.Web/module.manifest
tests/VirtoCommerce.CartModule.Tests/UnitTests/CartTotalsCalculationTests.cs
tests/VirtoCommerce.CartModule.Tests/UnitTests/ShoppingCartServiceImplUnitTests.cs
tests/VirtoCommerce.CartModule.Tests/VirtoCommerce.CartModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-10449

PT-10449: Update Crud and Search services

---

src/VirtoCommerce.CartModule.Data/Services/ShoppingCartBuilder.cs

fix: Returns wrong shipping method by code in GetShippingRatesAsync and GetAvailableShippingRatesAsync methods
https://virtocommerce.atlassian.net/browse/PT-12765

PT-12765: Returns wrong shipping method by code.

---

src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data/Repositories/CartDbContext.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/module.manifest

fix: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.
https://virtocommerce.atlassian.net/browse/PT-13179

PT-13179: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified

---

src/VirtoCommerce.CartModule.Core/Model/LineItem.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20230911171308_AddProductOuterId.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20230911171308_AddProductOuterId.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20230911171335_AddProductOuterId.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20230911171335_AddProductOuterId.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20230911171356_AddProductOuterId.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20230911171356_AddProductOuterId.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/LineItemEntity.cs

feat: Extend lineitem with Product Outer Id.
https://virtocommerce.atlassian.net/browse/PT-13550

PT-13550: Extend lineitem with Product Outer Id

---

src/VirtoCommerce.CartModule.Data/Services/DefaultShoppingCartTotalsCalculator.cs

https://virtocommerce.atlassian.net/browse/PT-13692

PT-13692: fix incorrect LineItemTotals calculations for unselected items

---

src/VirtoCommerce.CartModule.Core/Model/Search/ShoppingCartSearchCriteria.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartSearchService.cs

https://virtocommerce.atlassian.net/browse/PT-14606
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.408.0-pr-136-0c64.zip

PT-14606: add special search criteria flag for carts with no organization

---

src/VirtoCommerce.CartModule.Core/Model/ShoppingCart.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20231214154047_OrganizationName.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20231214154047_OrganizationName.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20231214154110_OrganizationName.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20231214154110_OrganizationName.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20231214154124_OrganizationName.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20231214154124_OrganizationName.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/ShoppingCartEntity.cs

fix: Organization Name is empty
https://virtocommerce.atlassian.net/browse/PT-14655
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.409.0-pr-138-e671.zip

PT-14655: Organization Name is empty

---

Directory.Build.props
src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data.MySql/VirtoCommerce.CartModule.Data.MySql.csproj
src/VirtoCommerce.CartModule.Data.PostgreSql/VirtoCommerce.CartModule.Data.PostgreSql.csproj
src/VirtoCommerce.CartModule.Data.SqlServer/VirtoCommerce.CartModule.Data.SqlServer.csproj
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/VirtoCommerce.CartModule.Web.csproj
src/VirtoCommerce.CartModule.Web/module.manifest
tests/VirtoCommerce.CartModule.Tests/VirtoCommerce.CartModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.800.0-pr-137-24a8.zip

PT-14740: .net 8

---

src/VirtoCommerce.CartModule.Core/Services/IWishlistService.cs
src/VirtoCommerce.CartModule.Data/Services/WishlistService.cs

https://virtocommerce.atlassian.net/browse/VCST-6
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.801.0-pr-139-6ff4.zip

VCST-6: add organizationId to FindProductsInWishlists

---

src/VirtoCommerce.CartModule.Core/Model/ShoppingCart.cs
src/VirtoCommerce.CartModule.Core/Services/IWishlistService.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20240319123828_AddLineItemsCount.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20240319123828_AddLineItemsCount.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20240319123813_AddLineItemsCount.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20240319123813_AddLineItemsCount.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20240319105457_AddLineItemsCount.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20240319105457_AddLineItemsCount.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/ShoppingCartEntity.cs
src/VirtoCommerce.CartModule.Data/Services/DefaultShoppingCartTotalsCalculator.cs
src/VirtoCommerce.CartModule.Data/Services/WishlistService.cs

https://virtocommerce.atlassian.net/browse/VCST-533
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.803.0-pr-141-751d.zip

VCST-533: add find product wishlist by products method, LineItemsCount to cart model

---

src/VirtoCommerce.CartModule.Data.MySql/MySqlCartRawDatabaseCommand.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/PostgreSqlCartRawDatabaseCommandcs.cs
src/VirtoCommerce.CartModule.Data.SqlServer/SqlServerCartRawDatabaseCommand.cs

https://virtocommerce.atlassian.net/browse/VCST-1309
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.807.0-pr-146-36e2.zip

VCST-1309: exclude Gift products from inWishlist

---

src/VirtoCommerce.CartModule.Data.MySql/Migrations/20240531113118_ResizeAddressFields.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20240531113118_ResizeAddressFields.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20240531113230_ResizeAddressFields.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20240531113230_ResizeAddressFields.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20240531113250_ResizeAddressFields.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20240531113250_ResizeAddressFields.cs
src/VirtoCommerce.CartModule.Data/Model/AddressEntity.cs
src/VirtoCommerce.CartModule.Data/Validation/AddressValidator.cs

- Resize AddressEntity fields according to customer AddressEntity fields
Need to resolve the issue with adding shipping address
```
"GraphQL.Execution.UnhandledError: Error trying to resolve field 'addOrUpdateCartShipment'.\n ---> FluentValidation.ValidationException: Validation failed: \n -- x[0].Shipments[0].DeliveryAddress.Organization: The length of 'Organization' must be 64 characters or fewer. You entered 67 characters. Severity: Error\n   at FluentValidation.AbstractValidator`1.RaiseValidationException(ValidationContext`1 context, ValidationResult result) in /_/src/FluentValidation/AbstractValidator.cs:line 531\n   at FluentValidation.AbstractValidator`1.ValidateInternalAsync(ValidationContext`1 context, Boolean useAsync, CancellationToken cancellation) in …
```

feat: Resize address fields according to customer address fields

---

src/VirtoCommerce.CartModule.Core/Model/Search/ShoppingCartSearchCriteria.cs
src/VirtoCommerce.CartModule.Data.MySql/MySqlCartRawDatabaseCommand.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/PostgreSqlCartRawDatabaseCommandcs.cs
src/VirtoCommerce.CartModule.Data.SqlServer/SqlServerCartRawDatabaseCommand.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartSearchService.cs
src/VirtoCommerce.CartModule.Data/Services/WishlistService.cs

https://virtocommerce.atlassian.net/browse/VCST-1416
https://virtocommerce.atlassian.net/browse/PT-14606
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.810.0-pr-149-9f40.zip

VCST-1416: Fix searching for wishlists

---

src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20241108110841_PromotionName.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20241108110841_PromotionName.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20241108110907_PromotionName.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20241108110907_PromotionName.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20241108110928_PromotionName.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20241108110928_PromotionName.cs
src/VirtoCommerce.CartModule.Data/Model/DiscountEntity.cs
src/VirtoCommerce.CartModule.Data/Model/DiscountEntityComparer.cs
src/VirtoCommerce.CartModule.Data/Repositories/CartDbContext.cs
src/VirtoCommerce.CartModule.Web/module.manifest

feat: Added "PromotionName" column to DiscountEntity
https://virtocommerce.atlassian.net/browse/VCST-1659
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.818.0-pr-157-33f4.zip

VCST-1659: Added "PromotionName" column to DiscountEntity

---

src/VirtoCommerce.CartModule.Core/VirtoCommerce.CartModule.Core.csproj
src/VirtoCommerce.CartModule.Data.MySql/VirtoCommerce.CartModule.Data.MySql.csproj
src/VirtoCommerce.CartModule.Data.PostgreSql/VirtoCommerce.CartModule.Data.PostgreSql.csproj
src/VirtoCommerce.CartModule.Data.SqlServer/VirtoCommerce.CartModule.Data.SqlServer.csproj
src/VirtoCommerce.CartModule.Data/Services/DefaultShoppingCartTotalsCalculator.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/module.manifest
tests/VirtoCommerce.CartModule.Tests/UnitTests/CartTotalsCalculationTests.cs
tests/VirtoCommerce.CartModule.Tests/VirtoCommerce.CartModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/VCST-244
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.819.0-pr-158-a262.zip

VCST-244: Calculate LineItem.ExtendedPrice properly

---

src/VirtoCommerce.CartModule.Core/Notifications/AbandonedCartEmailNotification.cs
src/VirtoCommerce.CartModule.Data/BackgroundJobs/AbandonedCartReminderJob.cs
src/VirtoCommerce.CartModule.Web/NotificationTemplates/AbandonedCartEmailNotification_body.html
src/VirtoCommerce.CartModule.Web/NotificationTemplates/AbandonedCartEmailNotification_sample.json

fix: Fixed links in abandoned cart email template
https://virtocommerce.atlassian.net/browse/VCST-2270
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.821.0-pr-160-2d38.zip

VCST-2270: Fixed links in abandoned cart email template

---

src/VirtoCommerce.CartModule.Core/Model/LineItem.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20241204152817_AddIsDiscountAmountRounded.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20241204152817_AddIsDiscountAmountRounded.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20241204152831_AddIsDiscountAmountRounded.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20241204152831_AddIsDiscountAmountRounded.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20241204152731_AddIsDiscountAmountRounded.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20241204152731_AddIsDiscountAmountRounded.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/LineItemEntity.cs
src/VirtoCommerce.CartModule.Data/Services/DefaultShoppingCartTotalsCalculator.cs
tests/VirtoCommerce.CartModule.Tests/UnitTests/CartTotalsCalculationTests.cs

https://virtocommerce.atlassian.net/browse/VCST-2305
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.823.0-pr-161-1ca4.zip

VCST-2305: Add ListTotal and IsDiscountAmountRounded to LineItem

---

src/VirtoCommerce.CartModule.Data/Services/ShoppingCartSearchService.cs
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs
tests/VirtoCommerce.CartModule.Tests/UnitTests/ShoppingCartServiceImplUnitTests.cs

https://virtocommerce.atlassian.net/browse/VCST-2784
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.826.0-pr-166-a1aa.zip

VCST-2784: Exclude inactive and missing payment and shipping methods

---

src/VirtoCommerce.CartModule.Data/Services/ShoppingCartService.cs

- Need to save extensibility of ShoppingCartService
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.828.0-pr-170-c3a8.zip

fix: ShoppingCartService. Make some methods protected and virtual.

---

src/VirtoCommerce.CartModule.Data.MySql/Migrations/20250428181839_AddAddressMiddleName.Designer.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/20250428181839_AddAddressMiddleName.cs
src/VirtoCommerce.CartModule.Data.MySql/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20250428182021_AddAddressMiddleName.Designer.cs
src/VirtoCommerce.CartModule.Data.PostgreSql/Migrations/20250428182021_AddAddressMiddleName.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20250428182048_AddAddressMiddleName.Designer.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/20250428182048_AddAddressMiddleName.cs
src/VirtoCommerce.CartModule.Data.SqlServer/Migrations/CartDbContextModelSnapshot.cs
src/VirtoCommerce.CartModule.Data/Model/AddressEntity.cs

https://virtocommerce.atlassian.net/browse/VCST-3168
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.829.0-pr-169-1e74.zip

VCST-3168: Added middle name to address

---

module.keep
src/VirtoCommerce.CartModule.Data/Services/ShoppingCartSearchService.cs
src/VirtoCommerce.CartModule.Data/VirtoCommerce.CartModule.Data.csproj
src/VirtoCommerce.CartModule.Web/module.manifest

feat: Adds search by phrase functionality to ShoppingCartSearchService. Example: criteria.Keyword = "StoreId:B2B-store Items.Sku:1513491" to return carts for the specific store and with specific products inside.
https://virtocommerce.atlassian.net/browse/VCST-3149
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.831.0-pr-171-5f01.zip

VCST-3149: Add search by phrase functionality to ShoppingCartSearchService
